name=PushButton
version=0.2.0
author=Tobias Knauss <tobias.knauss@web.de>
maintainer=Tobias Knauss <tobias.knauss@web.de>
sentence=Push Button with debouncing
paragraph=Debouncing for electrical push buttons.
category=Signal Input/Output
url=https://github.com/TobiasKnauss/ArduinoLib_PushButton
architectures=*
